"""Generate LaTeX macros for the September 2026 revision numbers from results/12-23.

The manuscript inputs ``sections/revision_numbers.tex``,
``sections/revision_seeds_table.tex`` and ``sections/revision_libsens_table.tex``;
regenerating them from the artifacts is
the only way new numbers enter the paper, so every printed value traces to a
JSON/CSV file by construction.

Usage:
  python3 src/make_revision_numbers.py --results-root results \
      --out-dir paper/ieee_aerospace_2027/sections
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os

import pandas as pd

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
M = 1e6
B = 1e9


def load(path):
    with open(path) as stream:
        return json.load(stream)


def fmt_int(x) -> str:
    return f'{int(round(x)):,}'


def fmt(x, nd=2) -> str:
    s = f'{x:,.{nd}f}'
    return s


def fmt_ceil(x, nd=2) -> str:
    """Round up, for quantities printed after 'at most' or 'within'."""
    k = 10 ** nd
    return f'{math.ceil(x * k - 1e-9) / k:,.{nd}f}'


def fmt_floor(x, nd=2) -> str:
    """Round down, for quantities printed after 'at least' or 'more than'."""
    k = 10 ** nd
    return f'{math.floor(x * k + 1e-9) / k:,.{nd}f}'


def fmt_sci(x: float) -> str:
    """Math-mode scientific notation; exact zeros print as $0$."""
    if abs(x) < 1e-12:
        return '$0$'
    mant, exp = f'{x:.1e}'.split('e')
    return f'${mant}\\times10^{{{int(exp)}}}$'


def macro(name: str, value, escape: bool = True) -> str:
    text = str(value)
    if escape:
        text = text.replace('_', '\\_').replace('%', '\\%').replace('&', '\\&')
    return f'\\newcommand{{\\{name}}}{{{text}}}'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--results-root', default=os.path.join(PROJECT_ROOT, 'results'))
    parser.add_argument('--out-dir', default=os.path.join(PROJECT_ROOT, 'paper', 'ieee_aerospace_2027', 'sections'))
    args = parser.parse_args()
    R = args.results_root
    lines = ['% Generated by src/make_revision_numbers.py -- do not edit by hand.',
             '% Source results root: ' + (os.path.relpath(os.path.abspath(R), PROJECT_ROOT)
                                          + '/ (repository-relative; machine and software\n%   versions are recorded in each stage manifest)'),
             f'% Generated: {dt.datetime.now().astimezone().isoformat()}']

    # ---- gate / rerun (results/12) -------------------------------------------
    gate = load(os.path.join(R, '12_revision_gate', 'gate_result.json'))
    red = gate['reduced_ef_rerun']
    env = gate['environment']
    lines += [
        macro('RerunDate', env['timestamp'][:10]),
        macro('RerunPython', env['python_version']),
        macro('RerunScipy', env['scipy_version']),
        macro('RerunNumpy', env['numpy_version']),
        macro('RerunMachine', env.get('hardware_model') or env.get('machine', 'unknown')),
        macro('RerunThreads', (env.get('thread_env') or {}).get('OMP_NUM_THREADS') or 'solver default'),
        macro('RerunCores', str(env.get('cpu_count') or 'unknown')),
        macro('RerunPruneS', fmt(red['pruning_time_s'], 2)),
        macro('RerunMasterS', fmt(red['master_assembly_plus_lp_time_s'], 2)),
        macro('RerunCertS', fmt(red['maximal_set_certification_time_s'], 2)),
        macro('RerunWallS', fmt(red['wall_time_excluding_pruning_s'], 2)),
        macro('RerunReducedObjB', fmt(red['certified_total_cost'] / B, 9)),
    ]
    rerun_path = os.path.join(R, '12_revision_gate', 'rerun_result.json')
    if os.path.exists(rerun_path):
        ccg = load(rerun_path)['ccg_rerun']
        lines += [
            macro('RerunCCGIters', str(ccg['num_iterations'])),
            macro('RerunCCGMasterS', fmt(ccg['master_solve_time_total_s'], 2)),
            macro('RerunCCGSepS', fmt(ccg['separation_time_total_s'], 2)),
            macro('RerunCCGWallS', fmt(ccg['wall_time_s'], 2)),
            macro('RerunCCGLPs', fmt_int(ccg['recourse_lps'])),
            macro('RerunCCGObjB', fmt(ccg['final_upper_bound'] / B, 9)),
        ]

    # ---- verify (results/13) --------------------------------------------------
    ver = load(os.path.join(R, '13_fixed_design_verification', 'verification_summary.json'))
    d = ver['designs']
    nom = d['nominal_only']
    lines += [
        macro('NominalQZero', fmt(nom['design']['q'][0], 3)),
        macro('NominalInvestM', fmt(nom['investment_cost'] / M, 2)),
        macro('NominalFullTotalB', fmt(nom['complete_library_total_cost'] / B, 3)),
        macro('NominalFullTotalBLong', fmt(nom['complete_library_total_cost'] / B, 9)),
        macro('NominalFullWorstB', fmt(nom['complete_library_worst_recourse'] / B, 9)),
        macro('NominalUnmet', fmt_int(nom['worst_unmet_tons'])),
        macro('NominalWorstID', str(nom['worst_scenario_id'])),
        macro('VerifyExactWorstM', fmt(d['exact']['complete_library_worst_recourse'] / M, 6)),
        macro('VerifyExactTotalB', fmt(d['exact']['complete_library_total_cost'] / B, 9)),
        macro('VerifySampledWorstM', fmt(d['sampled']['complete_library_worst_recourse'] / M, 6)),
        macro('VerifyNominalWorstM', fmt(nom['complete_library_worst_recourse'] / M, 6)),
        macro('VerifyExactMaximizers', str(d['exact']['num_cost_maximizers_within_tolerance'])),
        macro('VerifySampledMaximizers', str(d['sampled']['num_cost_maximizers_within_tolerance'])),
        macro('VerifyExactMaximizerIDs', ' and '.join(str(i) for i in d['exact']['cost_maximizers_within_tolerance'])),
        macro('VerifyEvalTimeS', fmt(d['exact']['eval_time_s'], 1)),
        macro('AuditDominated', fmt_int(d['exact']['monotonicity_audit']['dominated_matrices_checked'])),
        macro('AuditPairs', fmt_int(d['exact']['monotonicity_audit']['comparable_pairs_checked'])),
        macro('AuditViolations', str(sum(v['monotonicity_audit']['violations'] for v in d.values()))),
        macro('AuditDesigns', str(len(d))),
    ]

    # ---- dual (results/14) ----------------------------------------------------
    dual = load(os.path.join(R, '14_dual_oracle', 'dual_result.json'))
    sh = dual['shadow_prices']['sampled']['1295']
    q2_price = sh['first_stage_price_dollars_per_t_month'][2]
    q2_sub = sh['subgradient_wrt_q_dollars_per_t_month'][2]
    max_rel = max(x['rel_gap'] for v in dual['strong_duality'].values() for x in v)
    n_dual_checks = sum(len(v) for v in dual['strong_duality'].values())
    lines += [
        macro('ShadowSampledQTwoM', fmt(-q2_sub / M, 2)),
        macro('ShadowSampledQTwoPrice', fmt_int(q2_price)),
        macro('DualChecks', str(n_dual_checks)),
        macro('DualMaxRelGap', f'{max_rel:.0e}'.replace('e-', '\\times10^{-').replace('e+', '\\times10^{') + '}', escape=False),
        macro('LemmaBoundM', fmt(dual['lemma_bound_P_dollars'] / M, 0)),
    ]
    for name, key in (('nominal_only', 'Nominal'), ('sampled', 'Sampled'), ('exact', 'Exact')):
        run = dual['oracle'][name]['runs'][0]
        lines += [
            macro(f'Oracle{key}WorstM', fmt(run['worst_recourse'] / M, 6)),
            macro(f'Oracle{key}DiffDollars', fmt_sci(run['difference_vs_enumeration']), escape=False),
            macro(f'Oracle{key}TimeS', fmt(run['time_s'], 1)),
            macro(f'Oracle{key}Events', ', '.join('(' + ','.join(str(v) for v in e) + ')' for e in run['selected_events'])),
        ]
    lines.append(macro('OracleBinaries', str(dual['oracle']['exact']['runs'][0]['binaries'])))

    # ---- benders (results/15) -------------------------------------------------
    ben = load(os.path.join(R, '15_benders_cross_check', 'benders_result.json'))['benders']
    lines += [
        macro('BendersIters', str(ben['num_iterations'])),
        macro('BendersCuts', str(ben['num_cuts'])),
        macro('BendersLPs', fmt_int(ben['recourse_lps'])),
        macro('BendersObjB', fmt(ben['upper_bound'] / B, 9)),
        macro('BendersObjDiff', fmt_sci(ben['agreement_with_frozen']['objective_difference']), escape=False),
        macro('BendersQDiff', fmt_sci(ben['agreement_with_frozen']['q_max_abs_difference']), escape=False),
        macro('BendersFaceWidth', fmt_ceil(ben['optimal_face_max_width'], 3)),
        macro('BendersWallS', fmt(ben['wall_time_s'], 2)),
        macro('BendersFullCheckB', fmt(ben['final_complete_library_check']['complete_library_total_cost'] / B, 9)),
    ]

    # ---- ccgmax (results/16) --------------------------------------------------
    cm = load(os.path.join(R, '16_ccg_maximal_separation', 'ccg_maximal_result.json'))
    lines += [
        macro('CCGMaxIters', str(cm['num_iterations'])),
        macro('CCGMaxLPs', fmt_int(cm['recourse_lps'])),
        macro('CCGMaxSepS', fmt(sum(r['separation_time_s'] for r in cm['iterations']), 2)),
        macro('CCGMaxMasterS', fmt(sum(r['master_solve_time_s'] for r in cm['iterations']), 2)),
        macro('CCGMaxWallS', fmt(cm['wall_time_s'], 2)),
        macro('CCGMaxObjB', fmt(cm['final_upper_bound'] / B, 9)),
        macro('CCGMaxQDiff', fmt_sci(cm['agreement_with_frozen']['q_max_abs_difference']), escape=False),
    ]

    # ---- seeds (results/17) ---------------------------------------------------
    seeds = load(os.path.join(R, '17_sampling_seeds', 'seeds_summary.json'))
    frame = pd.read_csv(os.path.join(R, '17_sampling_seeds', 'seeds.csv'))
    rnd = frame[frame['label'] != 'even_index'].copy()
    lines += [
        macro('SeedsN', str(seeds['random_samples'])),
        macro('SeedsNMax', str(seeds['random_samples'] - 1)),
        macro('SeedsGapOverBillion', str(seeds['random_samples_with_gap_over_1e9'])),
        macro('SeedsGapOverMillion', str(seeds['random_samples_with_gap_over_1e6'])),
        macro('SeedsContainRef', str(seeds['random_samples_containing_1295'])),
        macro('SeedsContainBoth', str(seeds['random_samples_containing_both_reference_ids'])),
        macro('SeedsMinTotalB', fmt(seeds['complete_library_total_cost_min'] / B, 3)),
        macro('SeedsMaxTotalB', fmt(seeds['complete_library_total_cost_max'] / B, 3)),
        macro('SeedsInSampleDevPct', fmt_ceil(seeds['in_sample_rel_dev_from_exact_pct_max'], 3)),
        macro('SeedsInclusionPct', fmt(100 * seeds['inclusion_probability_single_encoding'], 2)),
        macro('SeedsInclusionBothPct', fmt(100 * seeds['inclusion_probability_both_reference_ids'], 2)),
        macro('SeedsSampleSize', fmt_int(seeds['sample_size'])),
        macro('SeedsEvenInSampleB', fmt(seeds['even_index_regression']['in_sample_total_cost'] / B, 9)),
        macro('SeedsEvenFullB', fmt(seeds['even_index_regression']['complete_library_total_cost'] / B, 9)),
    ]
    fail = rnd[rnd['gap_vs_exact_optimum'] > 1e9]
    with_ref = rnd[rnd['contains_1295']]
    without_ref = rnd[~rnd['contains_1295']]
    near = rnd[rnd['gap_vs_exact_optimum'] <= 1e9]
    separation_exact = bool(len(near) and set(near.index) == set(with_ref.index))
    lines += [
        macro('SeedsSeparationExact', 'yes' if separation_exact else 'NO'),
        macro('SeedsFailMinGapB', fmt(without_ref['gap_vs_exact_optimum'].min() / B, 3) if len(without_ref) else '--'),
    ]
    if not separation_exact:
        print('WARNING: encoding 1295 does NOT separate the outcomes exactly; '
              'the Section 6.4 separation sentence must be rewritten.')
    lines += [
        macro('SeedsFailMinTotalB', fmt(fail['complete_library_total_cost'].min() / B, 3) if len(fail) else '--'),
        macro('SeedsFailMaxTotalB', fmt(fail['complete_library_total_cost'].max() / B, 3) if len(fail) else '--'),
        macro('SeedsRefMaxGapM', fmt_ceil(with_ref['gap_vs_exact_optimum'].max() / M, 2) if len(with_ref) else '--'),
        macro('SeedsRefAllQTwoAtBound', 'yes' if len(with_ref) and (with_ref['q_mode_2'].sub(208.333333333).abs() < 1e-3).all() else 'no'),
        macro('SeedsOthersWorstIsRef', 'yes' if (rnd[~rnd['contains_1295']]['worst_scenario_id'] == 1295).all() else 'no'),
        macro('SeedsTotalLPs', fmt_int((seeds['random_samples'] + 1) * 1648)),
        macro('SeedsTotalLPsFull', fmt_int((seeds['random_samples'] + 1) * 29916)),
    ]

    # ---- seeds: relation between the design-generation objective and the complete-library value
    even_full = seeds['even_index_regression']['complete_library_total_cost']
    lo_row = rnd.loc[rnd['in_sample_total_cost'].idxmin()]
    hi_row = rnd.loc[rnd['in_sample_total_cost'].idxmax()]
    exact_opt = float((rnd['complete_library_total_cost'] - rnd['gap_vs_exact_optimum']).iloc[0])
    dev = 100 * (exact_opt - rnd['in_sample_total_cost']) / exact_opt
    lines += [
        macro('SeedsPearson', f"$-{abs(rnd['in_sample_total_cost'].corr(rnd['complete_library_total_cost'])):.2f}$", escape=False),
        macro('SeedsSpearman', f"$-{abs(rnd['in_sample_total_cost'].corr(rnd['complete_library_total_cost'], method='spearman')):.2f}$", escape=False),
        macro('SeedsInSampleDevPctMin', fmt_floor(dev.min(), 3)),
        macro('SeedsLowestInSampleB', fmt(lo_row['in_sample_total_cost'] / B, 4)),
        macro('SeedsLowestInSampleFullB', fmt(lo_row['complete_library_total_cost'] / B, 2)),
        macro('SeedsHighestInSampleB', fmt(hi_row['in_sample_total_cost'] / B, 4)),
        macro('SeedsHighestInSampleFullB', fmt(hi_row['complete_library_total_cost'] / B, 4)),
        macro('SeedsValueRatio', fmt_floor(rnd['complete_library_total_cost'].max() / rnd['complete_library_total_cost'].min(), 2)),
        macro('SeedsSameClassAsEven', str(int((rnd['complete_library_total_cost'].sub(even_full).abs() < 0.5e6).sum()))),
        macro('SeedsBetterHalfBillion', str(int((rnd['complete_library_total_cost'] < even_full - 0.5e9).sum()))),
        macro('SeedsWorseThirdBillion', str(int((rnd['complete_library_total_cost'] > even_full + 0.3e9).sum()))),
        macro('SeedsMedianB', fmt(rnd['complete_library_total_cost'].median() / B, 2)),
    ]
    assert rnd['in_sample_total_cost'].corr(rnd['complete_library_total_cost']) < 0, 'sign of the correlation changed'

    # ---- full extensive form over all distinct matrices (results/18) ------------------
    fe_path = os.path.join(R, '18_full_ef_attempt', 'full_ef_result.json')
    if os.path.exists(fe_path):
        fe = load(fe_path)
        ipm = load(os.path.join(R, '18_full_ef_attempt', 'full_ef_result_ipm.json'))
        assert fe['success'] and not ipm['success']
        lines += [
            macro('FullEFSolveS', fmt_int(fe['solve_time_s'])),
            macro('FullEFObjB', fmt(fe['total_cost'] / B, 9)),
            macro('FullEFObjDiff', fmt_sci(fe['agreement_with_frozen']['objective_difference']), escape=False),
            macro('FullEFQDiff', fmt_sci(fe['agreement_with_frozen']['q_max_abs_difference']), escape=False),
            macro('FullEFNonzeros', fmt_int(fe['dims']['nonzeros'])),
            macro('FullEFIPMTimeS', fmt_int(ipm['solve_time_s'])),
        ]
    else:
        print('WARNING: results/18_full_ef_attempt missing; FullEF macros not generated.')

    # ---- scenario-level consequence (results/19) ---------------------------------------
    sc = load(os.path.join(R, '19_scenario_level', 'scenario_level_summary.json'))
    sf, ds, xs = sc['sampled_failures'], sc['designs'], sc['exact_minus_sampled']
    assert sc['checks']['exact_never_beyond_startup'] and sc['checks']['sampled_unique_maximizer_is_1295']
    assert sf['all_are_pairs_on_modes_0_and_1'] and xs['cheaper_ids_equal_failure_ids']
    startup = sc['startup_penalty_dollars']
    in_sample = seeds['even_index_regression']['in_sample_total_cost']
    forced = sc['forced_depot_investment_dollars']
    ctrl = sc['controllable_investment_dollars']
    lines += [
        macro('ScenExactBeyond', str(ds['exact']['encodings_with_shortfall_beyond_startup'])),
        macro('ScenSampledFail', str(sf['count'])),
        macro('ScenSampledFailPct', fmt(sf['share_pct'], 2)),
        macro('ScenNominalFail', fmt_int(ds['nominal_only']['encodings_with_shortfall_beyond_startup'])),
        macro('ScenNominalFailPct', fmt(ds['nominal_only']['share_with_shortfall_beyond_startup_pct'], 1)),
        macro('ScenAboveInSample', str(sf['encodings_above_in_sample_worst_recourse'])),
        macro('ScenAboveInSamplePct', fmt(100 * sf['encodings_above_in_sample_worst_recourse'] / ds['sampled']['encodings'], 2)),
        macro('ScenFailMinDuration', str(sf['min_event_duration_months'])),
        macro('ScenFailMinOverlap', str(sf['min_months_both_primary_modes_out'])),
        macro('ScenFailExtraMin', fmt_floor(sf['extra_unmet_tons_min'], 1)),
        macro('ScenFailExtraMax', fmt_int(sf['extra_unmet_tons_max'])),
        macro('ScenSyncPairs', str(sf['synchronized_six_month_pairs'])),
        macro('ScenSyncLate', str(sf['synchronized_not_in_month_one'])),
        macro('ScenSyncLateExtra', ' and '.join(fmt_int(v) for v in sf['synchronized_not_in_month_one_extra_unmet_tons'])),
        macro('ScenSyncLastStart', str(max(sf['synchronized_start_months_one_based']))),
        macro('ScenNoMonthOneSampledB', fmt(ds['sampled']['no_month_one_outage']['total_cost'] / B, 3)),
        macro('ScenNoMonthOneSampledPct', fmt(ds['sampled']['no_month_one_outage']['increase_over_sampled_in_sample_pct'], 1)),
        macro('ScenNoMonthOneSampledUnmet', fmt_int(ds['sampled']['no_month_one_outage']['worst_unmet_tons'])),
        macro('ScenNoMonthOneExactB', fmt(ds['exact']['no_month_one_outage']['total_cost'] / B, 3)),
        macro('ScenNominalNetExactM', fmt(ds['exact']['nominal_scenario_total_net_of_startup'] / M, 2)),
        macro('ScenNominalNetSampledM', fmt(ds['sampled']['nominal_scenario_total_net_of_startup'] / M, 2)),
        macro('ScenNominalDiffPct', fmt(xs['nominal_scenario_difference_pct_of_net_total'], 3)),
        macro('ScenNominalDiffDollars', fmt_int(xs['nominal_scenario_difference_dollars'])),
        macro('ScenMaxExtraM', fmt_ceil(xs['max_extra_cost_dollars'] / M, 2)),
        macro('ScenMaxSavingB', fmt(xs['max_saving_dollars'] / B, 3)),
        macro('ScenExactExtraBoundT', fmt_ceil(sc['exact_extra_unmet_bound_tons'], 2)),
        macro('NetSampledInSampleM', fmt((in_sample - startup) / M, 1)),
        macro('NetSampledFullB', fmt(ds['sampled']['complete_library_total_net_of_startup'] / B, 3)),
        macro('NetExactFullM', fmt(ds['exact']['complete_library_total_net_of_startup'] / M, 1)),
        macro('InvestForcedM', fmt(forced / M, 0)),
        macro('InvestControlSampledM', fmt(ctrl['sampled'] / M, 3)),
        macro('InvestControlExactM', fmt(ctrl['exact'] / M, 3)),
        macro('InvestControlDiffPct', fmt(100 * abs(ctrl['sampled'] - ctrl['exact']) / ctrl['sampled'], 3)),
    ]

    # ---- support of the optimum, leave-one-out, closed form (results/20) ---------------
    sup = load(os.path.join(R, '20_support_certificate', 'support_certificate.json'))
    assert sup['closed_form_maximal_set']['sets_equal'] and sup['certificate']['closed']
    two = sup['subset_extensive_forms']['ids_1220_1295']
    loo = sup['leave_one_out_1295']
    only = sup['subset_extensive_forms']
    vec = lambda q: '(' + ', '.join(fmt(v, 3) for v in q) + ')'
    lines += [
        macro('SupportTwoVars', fmt_int(two['dims']['variables'])),
        macro('SupportTwoObjDiff', fmt_sci(two['objective_minus_exact_optimum']), escape=False),
        macro('SupportTwoQDiff', fmt_sci(two['q_max_abs_difference_from_exact']), escape=False),
        macro('SupportOnlyOutageAQ', vec(only['id_1295_only']['q'])),
        macro('SupportOnlyOutageBQ', vec(only['id_1220_only']['q'])),
        macro('LOOQTwo', fmt(loo['design']['q'][2], 1)),
        macro('LOOFullB', fmt(loo['complete_library_total_cost'] / B, 3)),
        macro('LOOOmitPct', fmt(loo['probability_uniform_sample_of_999_maximal_matrices_omits_it_pct'], 1)),
        macro('MaxDurationEvents', str(sup['closed_form_maximal_set']['maximum_duration_events'])),
    ]

    # ---- CCG from the nominal encoding (results/21) ------------------------------------
    cs = load(os.path.join(R, '21_ccg_start_sets', 'ccg_start_sets.json'))
    cmax, call = cs['nominal_start_maximal_separation'], cs['nominal_start_all_encoding_separation']
    for run in (cmax, call):
        assert run['converged'] and abs(run['objective_minus_exact_optimum']) <= 1.0
    assert cmax['added_ids_in_order'] == call['added_ids_in_order'] and cmax['num_iterations'] == call['num_iterations']
    ids = [str(i) for i in cmax['added_ids_in_order']]
    lines += [
        macro('CCGColdIters', str(cmax['num_iterations'])),
        macro('CCGColdActive', str(len(cmax['active_ids_final']))),
        macro('CCGColdMasterVars', fmt_int(cmax['final_master_variables'])),
        macro('CCGColdLPsMax', fmt_int(cmax['recourse_lps'])),
        macro('CCGColdLPsAll', fmt_int(call['recourse_lps'])),
        macro('CCGColdAddedIDs', ', '.join(ids[:-1]) + ', and ' + ids[-1]),
        macro('CCGColdObjB', fmt(cmax['total_cost'] / B, 9)),
    ]

    # ---- library sensitivity (results/22) -----------------------------------------------
    ls = load(os.path.join(R, '22_library_sensitivity', 'library_sensitivity.json'))['variants']
    by = {r['variant']: r for r in ls}
    assert all(r['closed_form_equals_filter'] and r['eta_matches_evaluation'] for r in ls)
    assert all(abs(r['q2_minus_prediction']) < 1e-3 for r in ls), 'supply-window formula no longer matches q2'
    sym, single = by['mode2_cap_6'], by['single_event']
    lines += [
        macro('LibSensSymQOne', fmt(sym['q'][1], 3)),
        macro('LibSensSymMaxUnmet', fmt_ceil(sym['maximal_set_evaluation']['max_unmet_tons_in_cost_min_solutions'], 1)),
        macro('LibSensSingleQ', vec(single['q'])),
        macro('LibSensSingleMaxUnmet', fmt_ceil(single['maximal_set_evaluation']['max_unmet_tons_in_cost_min_solutions'], 2)),
        macro('LibSensVariants', str(len(ls))),
    ]
    extra = [r['maximal_set_evaluation']['max_unmet_tons_in_cost_min_solutions'] - sc['startup_unmet_tons'] for r in ls]
    assert extra[0] < 1e-6, 'the study instance is expected to tolerate no shortfall beyond start-up'
    words = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']
    lines += [
        macro('LibSensTolerant', words[sum(1 for v in extra if v > 1e-6)]),
        macro('LibSensMaxExtraUnmet', fmt_ceil(max(extra), 1)),
    ]
    sens_rows = []
    for r in ls:
        caps = '(' + ','.join(str(v) for v in r['L_max']) + ')'
        sens_rows.append('    {} & {} & {} & {} & {} & {} & {} & {} \\\\'.format(
            caps, r['Gamma'], fmt_int(r['encodings']), fmt_int(r['maximal_matrices']),
            fmt(r['q'][0], 1), fmt(r['q'][1], 1), fmt(r['q'][2], 1), fmt(r['total_cost'] / B, 4)))
    sens_table = ['% Generated by src/make_revision_numbers.py -- do not edit by hand.',
                  '% columns: duration caps (modes 0,1,2) & event budget & encodings & maximal matrices & q_0 & q_1 & q_2 (t/mo) & optimum ($B)',
                  '\\newcommand{\\LibSensTableRows}{%'] + sens_rows + ['}']

    # ---- penalty scale (results/23) -------------------------------------------------------
    pen = load(os.path.join(R, '23_penalty_scale', 'penalty_scale.json'))['scales']
    tested = [r for r in pen if r['penalty_scale'] != 1.0]
    invariant = all(r['q_exact_max_abs_difference_from_baseline'] < 1e-3 and r['q_sampled_max_abs_difference_from_baseline'] < 1e-3
                    and abs(r['exact']['maximal_set_evaluation']['worst_unmet_tons'] - 300) < 1e-6
                    and abs(r['sampled']['maximal_set_evaluation']['worst_unmet_tons'] - 770) < 1e-6 for r in tested)
    low = min(pen, key=lambda r: r['penalty_scale'])
    lines += [
        macro('PenaltyInvariant', 'yes' if invariant else 'NO'),
        macro('PenaltyScales', str(len(tested))),
        macro('PenaltyLowIncreasePct', fmt(low['sampled_increase_pct'], 1)),
        macro('PenaltyLowBelowPct', fmt(low['exact_below_sampled_pct'], 1)),
    ]
    if not invariant:
        print('WARNING: capacity vectors or shortfalls change with the penalty scale; the Section 2 sentence must be rewritten.')

    # outcome-class table: group random samples by (q2, worst unmet)
    MIN_GROUP = 3
    rnd['q2r'] = rnd['q_mode_2'].round(0)
    groups = [(q2, g) for q2, g in rnd.groupby('q2r')]
    big = sorted([(q2, g) for q2, g in groups if len(g) >= MIN_GROUP], key=lambda kv: -kv[0])
    small = [g for q2, g in groups if len(g) < MIN_GROUP]

    def span(values, nd=3, sep='--', comma=False):
        lo, hi = min(values), max(values)
        f = (lambda v: f'{v:,.{nd}f}') if comma else (lambda v: f'{v:.{nd}f}')
        return f(lo) if f(lo) == f(hi) else f'{f(lo)}{sep}{f(hi)}'

    def row(g):
        return (len(g), int(g['contains_1295'].sum()),
                span(g['q_mode_2'].tolist(), 3),
                span((g['complete_library_total_cost'] / B).tolist(), 3),
                span(g['worst_unmet_tons'].tolist(), 0, comma=True))

    rows = []
    for _, g in big:
        n, ref, q2, val, unmet = row(g)
        rows.append(f'    {n} & {ref} & {q2} & {val} & {unmet} \\\\')
    if small:
        g = pd.concat(small)
        n, ref, q2, val, unmet = row(g)
        rows.append('    \\midrule')
        rows.append(f'    {n} & {ref} & {q2} & {val} & {unmet} \\\\')
    table = ['% Generated by src/make_revision_numbers.py -- do not edit by hand.',
             '% columns: samples & of which contain encoding 1295 & q_2 (t/mo) & complete-library value ($B) & associated unmet demand (t)',
             '\\newcommand{\\SeedsTableRows}{%']
    table += rows
    table += ['}']
    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, 'revision_numbers.tex'), 'w') as stream:
        stream.write('\n'.join(lines) + '\n')
    with open(os.path.join(args.out_dir, 'revision_seeds_table.tex'), 'w') as stream:
        stream.write('\n'.join(table) + '\n')
    with open(os.path.join(args.out_dir, 'revision_libsens_table.tex'), 'w') as stream:
        stream.write('\n'.join(sens_table) + '\n')
    print('\n'.join(lines))
    print('\n'.join(table))


if __name__ == '__main__':
    main()
